version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  user-service:
    build: ./user-service
    env_file: .env
    ports:
      - "${USER_SERVICE_PORT}:3001"
    depends_on:
      - mysql

  course-service:
    build: ./course-service
    env_file: .env
    ports:
      - "${COURSE_SERVICE_PORT}:3002"
    depends_on:
      - mysql

  content-service:
    build: ./content-service
    env_file: .env
    ports:
      - "${CONTENT_SERVICE_PORT}:3003"
    volumes:
      - ./content-data:/data/content
    depends_on:
      - mysql

  quiz-service:
    build: ./quiz-service
    env_file: .env
    ports:
      - "${QUIZ_SERVICE_PORT}:3004"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
