CREATE TABLE IF NOT EXISTS analytics_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  entity_id BIGINT,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(64) NOT NULL,
  params JSON,
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  url VARCHAR(512)
); 